locations:
  agents:
    - "05_agents"
  prompts:
    - "03_prompts"
  rulesets:
    - "01_rulesets"
  fragments:
    - "02_fragments"
  skills:
    - "04_skills"
  deployments:
    - "09_deployments"

tools:
  - windsurf
  - antigravity
  - github_copilot
  - claude
  - codex
  - cursor

env_vars:
  HOME_FOLDER: "~"
  PROJECTS_FOLDER: "~/Documents/Projects"
