id: ai-tools
version: 1.0.0
name: 'AI Tools Repository'
description: 'A unified mono-repository for AI agent configuration - define once in YAML, deploy everywhere'

context:
  overview: |
    A comprehensive solution for managing AI agent prompts, rules, skills, and tool configurations.
    Keep your "source of truth" in small, typed YAML manifests and automatically generate
    tool-specific artifacts for Windsurf, Claude Code, Cursor, GitHub Copilot, and other AI coding assistants.

    The repository provides a build system that transforms unified YAML manifests into
    tool-specific formats, ensuring consistency across different AI coding environments.
    It includes prompts for common tasks, agents for specific roles, rulepacks for coding standards,
    skills for tool integrations, and a project system for per-project configurations.

  purpose: 'Enable teams to manage AI coding assistant configurations as code, with version control, validation, and automated deployment'

tech_stack:
  languages:
    - typescript
    - yaml
    - markdown
  frontend: []
  backend:
    - node.js
  database: []
  infrastructure:
    - github-actions
    - git
  tools:
    - tsx
    - ajv
    - js-yaml
    - chalk
    - prettier

documentation:
  readme: 'README.md'
  main_docs:
    prompts: 'prompts/README.md'
    agents: 'docs/AGENTS.md'
    skills: 'skills/README.md'
    projects: 'projects/README.md'
    tools: 'docs/TOOLS.md'
    user_tools: 'docs/USER_TOOLS.md'
  development:
    style_guide: 'docs/STYLE_GUIDE.md'
    changelog: 'docs/CHANGELOG.md'
    planned_features: 'docs/PLANNED_FEATURES.md'
  schemas:
    prompt: 'schemas/prompt.schema.json'
    agent: 'schemas/agent.schema.json'
    rulepack: 'schemas/rulepack.schema.json'
    skill: 'schemas/skill.schema.json'
    project: 'schemas/project.schema.json'
    eval: 'schemas/eval.schema.json'

commands:
  validation:
    all: 'npm run validate'
    lint: 'npm run lint'
    format: 'npm run format'

  build:
    all: 'npm run build'
    docs: 'npm run docs'
    skills: 'npm run skills'

  generation:
    prompt_library: 'npm run prompt-library'
    prompt_html: 'npm run prompt-html'
    use_prompt: 'npm run use-prompt'

  projects:
    create: 'npm run project:create <name>'
    list: 'npm run project:list'
    generate: 'npm run project:generate <project-id>'
    deploy: 'npm run project:deploy <project-id>'

  testing:
    validate_and_build: 'npm test'
    full_ci: 'npm run ci'
    eval: 'npm run eval'

  cleanup:
    clean: 'npm run clean'

conventions:
  naming:
    - 'Use kebab-case for manifest IDs (e.g., write-tests, code-reviewer)'
    - 'Use kebab-case for file names (e.g., extract-method.yml)'
    - 'Use camelCase for TypeScript functions and variables'
    - 'Use PascalCase for TypeScript classes'

  patterns:
    - 'All manifests must be YAML files with .yml extension'
    - 'Follow JSON Schema definitions in schemas/ directory'
    - 'Use semantic versioning for manifest versions (semver)'
    - 'Include comprehensive descriptions (10-500 characters)'
    - 'Organize manifests by category in appropriate directories'

  structure:
    - 'prompts/ - Organized by category (refactor/, qa/, docs/)'
    - 'agents/ - Agent manifests defining roles and behaviors'
    - 'rulepacks/ - Coding standards and style rules'
    - 'skills/ - Tool integrations and capabilities'
    - 'projects/ - Project-specific configurations (global/ and local/)'
    - 'schemas/ - JSON Schema definitions for validation'
    - 'scripts/ - Build and utility scripts in TypeScript'
    - 'adapters/ - Generated tool-specific outputs (gitignored)'

  testing:
    - 'Run npm run validate before committing'
    - 'Ensure all schemas pass validation'
    - 'Test generated outputs with npm run build'
    - 'Verify tool-specific adapters are correct'

  documentation:
    - 'Update README.md for user-facing features'
    - 'Document new manifest types in appropriate docs/'
    - 'Include examples in manifest files'
    - 'Keep CHANGELOG.md updated for releases'
    - 'Add helpful comments in YAML manifests'

ai_tools:
  preferred_agents:
    - code-reviewer
    - feature-builder
    - bug-fixer
    - prompt-engineer

  preferred_rulepacks:
    - base
    - coding-typescript

  custom_rules:
    - 'Always use chalk for colored terminal output'
    - 'Use Ajv with ajv-formats for JSON Schema validation'
    - 'Export classes from scripts for reusability (e.g., ProjectGenerator)'
    - 'Use import.meta.url guards for CLI entry points'
    - 'Follow the existing manifest structure - id, version, description are required'
    - 'Generate tool-specific outputs in adapters/ directory (gitignored)'
    - 'Keep source manifests in prompts/, agents/, rulepacks/, skills/'
    - 'Use TypeScript strict mode with ES modules'
    - 'Prefer async/await over callbacks'
    - 'Use js-yaml for YAML parsing and dumping'

  excluded_agents:
    - kotlin-style-enforcer

  excluded_rulepacks:
    - coding-kotlin
    - coding-java
    - coding-python

metadata:
  repository: 'https://github.com/cleanshipcz/ai-tools'
  maintainers:
    - 'cleanshipcz'
  created: '2025-11-15'
  updated: '2025-11-15'
  tags:
    - ai
    - tooling
    - configuration
    - mono-repository
    - yaml
    - prompts
    - agents
    - code-generation
