package cz.cleanship.aitools.engine.tools.adapters.github

import cz.cleanship.aitools.engine.io.CountingOutput
import cz.cleanship.aitools.engine.models.ProjectManifest
import cz.cleanship.aitools.engine.models.PromptVariable
import cz.cleanship.aitools.engine.models.ToolType
import cz.cleanship.aitools.engine.services.ExportService
import cz.cleanship.aitools.engine.tools.AgentContext
import cz.cleanship.aitools.engine.tools.FeatureContext
import cz.cleanship.aitools.engine.tools.GlobalContext
import cz.cleanship.aitools.engine.tools.Printers
import cz.cleanship.aitools.engine.tools.PromptContext
import cz.cleanship.aitools.engine.tools.SkillContext
import cz.cleanship.aitools.engine.tools.ToolAdapter
import org.slf4j.LoggerFactory
import java.io.File

class GitHubCopilotAdapter(
    private val printers: Printers = Printers,
    private val exportService: ExportService = ExportService(),
) : ToolAdapter {

    override val toolType: ToolType = ToolType.GITHUB_COPILOT

    override fun prepare(projectDir: File, project: ProjectManifest) {
        // Every file in these three directories is generated by this adapter and rewritten on each export,
        // so wiping them unconditionally - rather than only when the project-global `deploy.replace` flag is
        // set - can never remove anything but our own previous output. Without it, files from retired naming
        // schemes linger and keep polluting the VS Code prompt picker. `.github` itself is deliberately left
        // alone because it also holds `workflows/`, and `copilot-instructions.md` is overwritten in place.
        promptsDir(projectDir).deleteRecursively()
        instructionsDir(projectDir).deleteRecursively()
        agentsDir(projectDir).deleteRecursively()
    }

    override fun export(projectDir: File, globalContext: GlobalContext) = exportService.export(
        globalContext.project,
        githubDir(projectDir).resolve("copilot-instructions.md"),
    ) {
        printers.globalFilePrinter.print(globalContext, it)
    }

    override fun export(projectDir: File, promptContext: PromptContext) = exportService.export(
        promptContext.prompt,
        promptsDir(projectDir).resolve("prompt-${promptContext.prompt.id}.prompt.md"),
    ) {
        val prompt = promptContext.prompt
        it.appendText(frontmatter(prompt.id, prompt.description, argumentHint(prompt.variables)))
        printers.promptPrinter.print(promptContext, InputPlaceholderOutput(it, prompt.variables))
    }

    override fun export(projectDir: File, agentContext: AgentContext) = exportService.export(
        agentContext.agent,
        agentsDir(projectDir).resolve("${agentContext.agent.id}.agent.md"),
    ) {
        val agent = agentContext.agent
        it.appendText(frontmatter(agent.id, agent.description))
        val body = CountingOutput(it)
        printers.agentPrinter.print(agentContext, body)
        if (body.characterCount > MAX_AGENT_BODY_CHARACTERS) {
            LOG.warn(
                "Agent {} has a body of {} characters, exceeding the GitHub Copilot custom agent limit of {} characters",
                agent.id,
                body.characterCount,
                MAX_AGENT_BODY_CHARACTERS,
            )
        }
    }

    override fun export(projectDir: File, featureContext: FeatureContext) = exportService.export(
        featureContext.feature,
        instructionsDir(projectDir).resolve("feature-${featureContext.feature.id}.instructions.md"),
    ) {
        it.appendText(header)
        printers.featurePrinter.print(featureContext, it)
    }

    override fun export(projectDir: File, skillContext: SkillContext) {
        val skill = skillContext.skill
        exportService.export(
            skill,
            promptsDir(projectDir).resolve("skill-${skill.id}.prompt.md"),
        ) {
            it.appendText(frontmatter(skill.id, skill.description))
            printers.skillPrinter.print(skillContext, it)
        }
        exportService.copySkillFiles(
            skill.files,
            skillContext.sourceDir,
            promptsDir(projectDir).resolve("skill-${skill.id}"),
        )
    }

    private fun githubDir(projectDir: File) = projectDir.resolve(".github")

    private fun promptsDir(projectDir: File) = githubDir(projectDir).resolve("prompts")

    private fun instructionsDir(projectDir: File) = githubDir(projectDir).resolve("instructions")

    private fun agentsDir(projectDir: File) = githubDir(projectDir).resolve("agents")

    private fun frontmatter(name: String, description: String, argumentHint: String? = null) = buildString {
        appendLine("---")
        appendLine("name: $name")
        appendLine("description: ${description.replace("\n", " ")}")
        if (argumentHint != null) {
            appendLine("argument-hint: $argumentHint")
        }
        appendLine("---")
    }

    /**
     * Renders the declared variables in manifest order as `<required>` and `[optional]` hints, or null when
     * the prompt declares none - `argument-hint` is then omitted from the frontmatter entirely.
     */
    private fun argumentHint(variables: List<PromptVariable>) = variables
        .takeIf { it.isNotEmpty() }
        ?.joinToString(" ") { if (it.required) "<${it.name}>" else "[${it.name}]" }

    companion object {
        private val LOG = LoggerFactory.getLogger(GitHubCopilotAdapter::class.java)

        /** Documented body limit of a GitHub Copilot custom agent profile. */
        private const val MAX_AGENT_BODY_CHARACTERS = 30_000

        private val header =
            """
            ---
            applyTo: "**/*"
            ---
            
            """.trimIndent()
    }
}
